services:
  web:
    build: .
    image: mywebapp
    ports:
      - "15000:5000"
    depends_on:
      - db
      - keycloak
    networks:
      - frontend
      - backend
    environment:
      OIDC_CLIENT_ID: flask-client
      OIDC_CLIENT_SECRET: flask-secret
      OIDC_DISCOVERY_URL: http://54.234.242.39:8080/realms/wk8app/.well-known/openid-configuration
    read_only: true
    security_opt:
      - no-new-privileges:true
    mem_limit: 256m
    pids_limit: 100

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: mydb
    networks:
      - backend

  keycloak-db:
    image: postgres:13
    container_name: keycloak_db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: kcpassword
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    networks:
      - backend

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    command: start-dev --hostname-strict=false --hostname-strict-https=false
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: kcpassword
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
     
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-db
    networks:
      - backend
      - frontend

volumes:
  keycloak_db_data:

networks:
  frontend:
  backend:
